FROM nvcr.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

# 1. 필수 시스템 패키지 설치
RUN apt-get update && apt-get install -y \
    apt-utils build-essential ca-certificates curl gpg kmod file \
    libelf-dev libglvnd-dev pkg-config wget vim zlib1g-dev \
    libncurses5-dev libgdbm-dev libnss3-dev libssl-dev \
    libreadline-dev libffi-dev software-properties-common coreutils \
    && rm -rf /var/lib/apt/lists/*


ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    apt-get update && \
    apt-get install -y tzdata && \
    dpkg-reconfigure -f noninteractive tzdata

ENV CONDA_DIR=/opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH
ARG INSTALLER_URL_LINUX64=https://repo.anaconda.com/miniconda/Miniconda3-py311_26.1.1-1-Linux-x86_64.sh
ARG SHA256SUM_LINUX64=52d1f19154b0716d7dc0872f0d858702640da08a4e53fd0035ba988608203d6b

# [1단계] 다운로드 및 무결성 검사
RUN set -x && \
    wget "${INSTALLER_URL_LINUX64}" -O miniconda.sh -q && \
    echo "${SHA256SUM_LINUX64}  miniconda.sh" > shasum && \
    sha256sum --check shasum && \
    bash miniconda.sh -b -p ${CONDA_DIR} && \
    rm miniconda.sh shasum

# [2단계] 시스템 경로 및 셸 설정
# 여기서 터진다면: 심볼릭 링크 생성 실패 혹은 파일 경로 오타
RUN set -x && \
    ln -s ${CONDA_DIR}/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". ${CONDA_DIR}/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate" >> ~/.bashrc
# [3단계] 약관 동의 및 용량 최적화 (Clean up)
# 여기서 터진다면: conda 명령어 인식 불가 혹은 라이선스 동의 모듈 누락
RUN set -x && \
    ${CONDA_DIR}/bin/conda tos accept && \
    ${CONDA_DIR}/bin/conda remove --force-remove -y conda-anaconda-tos && \
    rm -rf ~/.conda/tos && \
    find ${CONDA_DIR}/ -follow -type f -name '*.a' -delete && \
    find ${CONDA_DIR}/ -follow -type f -name '*.js.map' -delete

# 최신 pip 업그레이드 후, Jupyter Lab 설치
RUN conda install -y -c conda-forge jupyterlab nb_conda_kernels && \
    conda clean -afy

WORKDIR /home/jupyter

RUN echo "[global]\nindex-url = http://pypi.smc.com/simple\ntrusted-host = pypi.smc.com" > /etc/pip.conf
COPY jupyter_lab_config.py /home/jupyter/jupyter_lab_config.py

# Bash를 실행하고, 환경 설정을 불러온 뒤 주피터를 실행하도록 강제함
CMD ["/opt/conda/bin/jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--config=/etc/jupyter/jupyter_lab_config.py"]